# Generated by Django 4.2.7 on 2025-11-16 13:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_price_max_service_price_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='requires_security_deposit',
            field=models.BooleanField(default=False, help_text='Check if this service requires a security deposit'),
        ),
        migrations.AddField(
            model_name='service',
            name='security_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Security deposit amount (refundable after service completion)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='service',
            name='security_deposit_description',
            field=models.TextField(blank=True, help_text='Additional notes about the security deposit (e.g., conditions for refund)'),
        ),
    ]
