# Generated by Django 4.2.7 on 2025-11-15 07:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='brand',
            field=models.CharField(blank=True, help_text='Equipment brand/manufacturer', max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair')], default='excellent', max_length=20),
        ),
        migrations.AddField(
            model_name='equipment',
            name='model_number',
            field=models.CharField(blank=True, help_text='Model number or identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rent_price_daily',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alias for price_per_day', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='equipment',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description for listings', max_length=300),
        ),
        migrations.AddField(
            model_name='equipment',
            name='specifications',
            field=models.TextField(blank=True, help_text='Technical specifications'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='usage_instructions',
            field=models.TextField(blank=True, help_text='How to use this equipment'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
