# Generated by Django 5.2.1 on 2025-11-22 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_servicebooking_fk'),
        ('payments', '0004_make_payment_method_nullable'),
    ]

    operations = [
    ]
