# Generated by Django 5.2.1 on 2025-11-22 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_merge_20251122_1147'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending verification'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('partial', 'Partially Paid')], default='unpaid', max_length=20),
        ),
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash After Service'), ('online', 'Online Payment (QR)')], max_length=20)),
                ('qr_code_url', models.URLField(blank=True, help_text='Optional QR image or payment link', null=True)),
                ('bank_info', models.TextField(blank=True, help_text='Bank account / UPI / other details', null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_payment_methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
