# Generated by assistant: create ServiceBooking model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_final_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('service_address', models.TextField(help_text='Where the service will be provided')),
                ('service_price', models.DecimalField(max_digits=10, decimal_places=2)),
                ('additional_charges', models.DecimalField(default=0.0, max_digits=10, decimal_places=2)),
                ('final_price', models.DecimalField(blank=True, help_text='Final price set by admin/provider after assessment (overrides service_price in totals)', null=True, max_digits=10, decimal_places=2)),
                ('total_amount', models.DecimalField(max_digits=10, decimal_places=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('patient_notes', models.TextField(blank=True, help_text='Special instructions from patient')),
                ('provider_notes', models.TextField(blank=True, help_text='Provider notes after service')),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_service_bookings', to='accounts.user')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_service_bookings', to='accounts.user')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='services.service')),
            ],
            options={
                'db_table': 'service_bookings',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['patient', 'status'], name='appointments_se_patient_2f3b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['provider', 'status'], name='appointments_se_provider_0a7c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['appointment_date', 'status'], name='appointments_se_appointm_4a9f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['created_at'], name='appointments_se_created_3b1a2d_idx'),
        ),
    ]
