# Generated by Django 5.2.1 on 2025-11-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_migrate_appointments_to_servicebooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicebooking',
            options={'ordering': ['-appointment_date', '-appointment_time'], 'verbose_name': 'Service Booking', 'verbose_name_plural': 'Service Bookings'},
        ),
        migrations.RenameIndex(
            model_name='servicebooking',
            new_name='service_boo_patient_5ed1ef_idx',
            old_name='appointments_se_patient_2f3b1f_idx',
        ),
        migrations.RenameIndex(
            model_name='servicebooking',
            new_name='service_boo_provide_4aa19e_idx',
            old_name='appointments_se_provider_0a7c1b_idx',
        ),
        migrations.RenameIndex(
            model_name='servicebooking',
            new_name='service_boo_appoint_9eefd3_idx',
            old_name='appointments_se_appointm_4a9f2c_idx',
        ),
        migrations.RenameIndex(
            model_name='servicebooking',
            new_name='service_boo_created_585417_idx',
            old_name='appointments_se_created_3b1a2d_idx',
        ),
        migrations.AddField(
            model_name='personalappointment',
            name='patient_phone',
            field=models.CharField(blank=True, help_text='Phone number provided by patient for this appointment', max_length=32),
        ),
        migrations.AlterField(
            model_name='personalappointment',
            name='location_address',
            field=models.TextField(blank=True, help_text='Optional address (only needed for in-person bookings)'),
        ),
        migrations.AlterField(
            model_name='personalappointment',
            name='location_type',
            field=models.CharField(choices=[('video', 'Video Call'), ('phone', 'Phone Call')], default='video', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
